# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY src ./src

# Build
RUN npm run build

# Production env
ENV NODE_ENV=production

# Expose no HTTP port; uses stdio

# Start the server
CMD ["node", "build/index.js"]
